title: libqtkmz.so
description: >
  雑多なメモや記録
baseurl: ""
url: "https://github.com/qtkmz/"
twitter_username: qtkmz
github_username:  qtkmz
timezone: Asia/Tokyo
theme: jekyll-theme-midnight
markdown: kramdown
